### ISSUE TITLE
Plugin crashed when using ssh_key_path in the volume object

### ISSUE THREAD

**Issue by koboltmarky** [profitbricks/terraform-provider-profitbricks#1]
Hi,

when we use the ssh_key_path variable the terraform apply command failed with: 

panic: runtime error: invalid memory address or nil pointer dereference
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks: [signal 0xb code=0x1 addr=0x0 pc=0x476a46]
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks: 
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks: goroutine 162 [running]:
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks: panic(0xab6a00, 0xc82000a150)
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks:    /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks: github.com/profitbricks/terraform-provider-profitbricks/provider.getSshKey(0xc8202bca20, 0xc8202e82a0, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks:    /Users/jasmin/go/src/github.com/profitbricks/terraform-provider-profitbricks/provider/resource_profitbricks_server.go:600 +0x386
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks: github.com/profitbricks/terraform-provider-profitbricks/provider.resourceProfitBricksServerCreate(0xc8202bca20, 0x9a06c0, 0xc820341840, 0x0, 0x0)
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks:    /Users/jasmin/go/src/github.com/profitbricks/terraform-provider-profitbricks/provider/resource_profitbricks_server.go:262 +0xddc
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks: github.com/profitbricks/terraform-provider-profitbricks/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc8203d6360, 0xc820525840, 0xc82041cd70, 0x9a06c0, 0xc820341840, 0xc8202e8401, 0x0, 0x0)
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks:    /Users/jasmin/go/src/github.com/profitbricks/terraform-provider-profitbricks/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:162 +0x29a
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks: github.com/profitbricks/terraform-provider-profitbricks/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc82033eae0, 0xc820525700, 0xc820525840, 0xc82041cd70, 0x1, 0x0, 0x0)
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks:    /Users/jasmin/go/src/github.com/profitbricks/terraform-provider-profitbricks/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:176 +0x1ed
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks: github.com/profitbricks/terraform-provider-profitbricks/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc82033a4e0, 0xc820490b40, 0xc82041d280, 0x0, 0x0)
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks:    /Users/jasmin/go/src/github.com/profitbricks/terraform-provider-profitbricks/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:460 +0x76
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks: reflect.Value.call(0xa65060, 0xb641b8, 0x13, 0xb95c30, 0x4, 0xc8206ebec8, 0x3, 0x3, 0x0, 0x0, ...)
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks:    /usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:435 +0x120d
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks: reflect.Value.Call(0xa65060, 0xb641b8, 0x13, 0xc8206ebec8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks:    /usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:303 +0xb1
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks: net/rpc.(*service).call(0xc8203caf80, 0xc8203caf40, 0xc8203d23b0, 0xc8200a1a00, 0xc82033acc0, 0x96f6a0, 0xc820490b40, 0x16, 0x96f700, 0xc82041d280, ...)
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks:    /usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:383 +0x1c2
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks: created by net/rpc.(*Server).ServeCodec
2016/09/06 14:55:52 [DEBUG] plugin: terraform-provider-profitbricks:    /usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:477 +0x49d
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteState
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalIf
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteState
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteDiff
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteState
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalApplyPost
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalIf
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteState
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteDiff
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalApplyPost
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* profitbricks_server.jumphost: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* profitbricks_server.master03: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_server.jumphost: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_server.master03: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* profitbricks_server.jumphost: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* profitbricks_server.master03: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_server.jumphost: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_server.master03: unexpected EOF
2016/09/06 14:55:52 [TRACE] [walkApply] Exiting eval tree: profitbricks_server.jumphost
2016/09/06 14:55:52 [TRACE] [walkApply] Exiting eval tree: profitbricks_server.master03
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteState
2016/09/06 14:55:52 [DEBUG] vertex provisioner.file (close), got dep: profitbricks_server.jumphost
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalIf
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteState
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteState
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteState
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteDiff
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalApplyPost
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* profitbricks_server.master01: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_server.master01: unexpected EOF
2016/09/06 14:55:52 [DEBUG] vertex profitbricks_nic.jumphost_nic, got dep: profitbricks_server.jumphost
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* profitbricks_server.master01: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_server.master01: unexpected EOF
2016/09/06 14:55:52 [DEBUG] vertex profitbricks_nic.jumphost_nic, got dep: provider.profitbricks
2016/09/06 14:55:52 [TRACE] [walkApply] Exiting eval tree: profitbricks_server.master01
2016/09/06 14:55:52 [DEBUG] vertex profitbricks_nic.jumphost_nic, got dep: profitbricks_datacenter.main
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalIf
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteState
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteState
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteDiff
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalApplyPost
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalIf
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* profitbricks_server.master02: unexpected EOF
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteState
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_server.master02: unexpected EOF
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteDiff
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* profitbricks_server.master02: unexpected EOF
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalApplyPost
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_server.master02: unexpected EOF
2016/09/06 14:55:52 [TRACE] [walkApply] Exiting eval tree: profitbricks_server.master02
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalIf
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteState
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalWriteDiff
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* profitbricks_server.agent02: unexpected EOF
2016/09/06 14:55:52 [DEBUG] root: eval: *terraform.EvalApplyPost
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_server.agent02: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* profitbricks_server.agent01: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* profitbricks_server.agent02: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_server.agent01: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_server.agent02: unexpected EOF
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* profitbricks_server.agent01: unexpected EOF
2016/09/06 14:55:52 [TRACE] [walkApply] Exiting eval tree: profitbricks_server.agent02
2016/09/06 14:55:52 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_server.agent01: unexpected EOF
2016/09/06 14:55:52 [TRACE] [walkApply] Exiting eval tree: profitbricks_server.agent01
2016/09/06 14:55:52 [DEBUG] vertex provisioner.remote-exec (close), got dep: profitbricks_server.agent01
2016/09/06 14:55:52 [DEBUG] vertex provisioner.remote-exec (close), got dep: profitbricks_server.master03
2016/09/06 14:55:52 [DEBUG] vertex provisioner.remote-exec (close), got dep: profitbricks_server.master02
2016/09/06 14:55:52 [DEBUG] vertex provisioner.remote-exec (close), got dep: profitbricks_server.agent02
2016/09/06 14:55:52 [DEBUG] vertex provisioner.remote-exec (close), got dep: profitbricks_server.jumphost
2016/09/06 14:55:52 [DEBUG] vertex provisioner.remote-exec (close), got dep: profitbricks_server.master01
2016/09/06 14:55:52 [DEBUG] vertex profitbricks_firewall.jumphost_ping, got dep: profitbricks_server.jumphost
2016/09/06 14:55:52 [DEBUG] vertex profitbricks_firewall.jumphost_ping, got dep: provider.profitbricks
2016/09/06 14:55:52 [DEBUG] vertex profitbricks_firewall.jumphost_ping, got dep: profitbricks_datacenter.main
2016/09/06 14:55:52 [DEBUG] vertex provider.profitbricks (close), got dep: profitbricks_server.agent01
2016/09/06 14:55:52 [DEBUG] vertex provider.profitbricks (close), got dep: profitbricks_nic.jumphost_nic
2016/09/06 14:55:52 [DEBUG] vertex provider.profitbricks (close), got dep: profitbricks_server.master03
2016/09/06 14:55:52 [DEBUG] vertex provider.profitbricks (close), got dep: profitbricks_server.master02
2016/09/06 14:55:52 [DEBUG] plugin: /usr/local/bin/terraform-provider-profitbricks: plugin process exited
2016/09/06 14:55:52 [DEBUG] vertex provider.profitbricks (close), got dep: profitbricks_lan.jumphost_lan
2016/09/06 14:55:52 [DEBUG] vertex provider.profitbricks (close), got dep: profitbricks_firewall.jumphost_ping
2016/09/06 14:55:52 [DEBUG] vertex provider.profitbricks (close), got dep: profitbricks_ipblock.jumphost_ip
2016/09/06 14:55:52 [DEBUG] vertex provider.profitbricks (close), got dep: provider.profitbricks
2016/09/06 14:55:52 [DEBUG] vertex provider.profitbricks (close), got dep: profitbricks_server.agent02
2016/09/06 14:55:52 [DEBUG] vertex provider.profitbricks (close), got dep: profitbricks_datacenter.main
2016/09/06 14:55:52 [DEBUG] vertex provider.profitbricks (close), got dep: profitbricks_server.jumphost
2016/09/06 14:55:52 [DEBUG] vertex provider.profitbricks (close), got dep: profitbricks_server.master01
2016/09/06 14:55:52 [DEBUG] vertex root, got dep: provider.profitbricks (close)
2016/09/06 14:55:52 [DEBUG] vertex root, got dep: provisioner.remote-exec (close)
2016/09/06 14:55:52 [DEBUG] vertex root, got dep: provisioner.file (close)
2016/09/06 14:55:52 [TRACE] Preserving existing state lineage "90ebbf92-0a17-4743-968e-a11d80c14c0e"
2016/09/06 14:55:52 [DEBUG] plugin: waiting for all plugin processes to complete...
2016/09/06 14:55:52 [DEBUG] plugin: /usr/local/bin/terraform: plugin process exited
2016/09/06 14:55:52 [DEBUG] plugin: /usr/local/bin/terraform: plugin process exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

Using the image_password variable works.

Greets
Marc

**Comment by jasminSPC** [comment]
I've just tried to replicate this and was not able to achieve this error. 
I've used this https://github.com/profitbricks/terraform-provider-profitbricks/tree/master/example to create defined infrastructure, and I also tried removing the ssh key path and I also provided incorrect path but nothing resulted in anything similar.

Could please you provide me more details?

**Comment by jasminSPC** [comment]
I was able to replicate this scenario when I used an empty ssh key file. I've added a fix for it and released the latest binaries under version[ v.1.0.1](https://github.com/profitbricks/terraform-provider-profitbricks/releases/tag/v1.0.1)

Now the error should look something like this:
```
* profitbricks_server.database: Error fetching sshkeys (File /Users/jasmin/go/sandbox/tst contains nothing)
```

I hope this helps

**Comment by jasminSPC** [comment]
@koboltmarky I'm going to close this issue. If it happens again, feel free to reopen it.
