### ISSUE TITLE
ssh_key_path problem

### ISSUE THREAD

**Issue by koboltmarky** [profitbricks/terraform-provider-profitbricks#18]
Hi,

i tried the new Terraform v0.8.5 today. Before i used a older version with the terraform-provider-profitbricks
binary I want to use my public ssh key with the volume. Before the update the following syntax worked:

  `ssh_key_path = ["${var.ssh_keys}"]`

With the new version i get the following error:

  * profitbricks_server.webserver: volume.0.ssh_key_path must be a single value, not a list

Converting the list to a single value:

 * ssh_key_path = "${var.ssh_keys}"

i get the following error:

`profitbricks_server.webserver: Error fetching sshkeys (File XXX/id_rsa.pub contains nothing)`

Also the documentation is a little bit strange. From the terrafrom website:

```
resource "profitbricks_volume" "example" {
  datacenter_id = "${profitbricks_datacenter.example.id}"
  server_id = "${profitbricks_server.example.id}"
  image_name = "${var.ubuntu}"
  size = 5
  disk_type = "HDD"
  sshkey_path = "${var.private_key_path}"
  bus = "VIRTIO"
}

```

From your github example:

```
volume {
    name           = "system"
    image_name     = "${var.ubuntu}"
    size           = 5
    disk_type      = "SSD"
    ssh_key_path   = ["${var.ssh_keys}"]
    availability_zone = "AUTO"
  }
```

Use the private key really ?

Greets 
Marc

**Comment by jasminSPC** [comment]
How does your `variables.tf` look like?
It should contain something like this:
```
variable "ssh_keys" {
  description = "List of SSH Keys to be added to the VMs"

  default = ["/home/{your_username}/.ssh/your_public_key",
    "/home/ANOTHER-USER/.ssh/another_public_key",
  ]
}
```

From the error message you pasted it seems that the path to the ssh_key is invalid e.g. pointing to non-existent `id_rsa.pub`

In order to use some other value you can do following:
```
    ssh_key_path   = ["/path/to/private/ssh/key"]
```
make sure you provide correct path.

**Comment by koboltmarky** [comment]
That is my variables.tf:

variable "ssh_keys" {
  description = "List of SSH Keys to be added to the VMs"
  default = ["/home/xxxx/.ssh/sloppy/id_rsa.pub"]
}

The path is right, the same file worked before i updated to the new terraform version

**Comment by jasminSPC** [comment]
let me give it a try.

**Comment by koboltmarky** [comment]
i'm confused using my private key works

**Comment by jasminSPC** [comment]
It seems that the upstream version of ProfitBricks provider and the provider as third party plugin are different. And process of getting the latest changes in the upstream repo takes a while. 

So I would suggest that you install this https://github.com/profitbricks/terraform-provider-profitbricks/releases/tag/v1.1.1

I'm sorry for the inconvenience

**Comment by koboltmarky** [comment]
No problem, but only for my understanding:

ssh_key_path = List of my public keys ?
And ssh_key_path and not sshkey_path ?

**Comment by jasminSPC** [comment]
This would be correct:
`ssh_key_path = ["${var.ssh_keys}"]`  

Also you can reference [this](https://github.com/profitbricks/terraform-provider-profitbricks/blob/master/example/main.tf)

**Comment by koboltmarky** [comment]
Here is also a typo in the documentation:
https://www.terraform.io/docs/providers/profitbricks/r/profitbricks_volume.html

Thx for your help

**Comment by jasminSPC** [comment]
https://github.com/hashicorp/terraform/pull/11520
We have a pending PR here. Once it is published you will be able to use ProfitBricks provider without installing additional plugins.
