### ISSUE TITLE
PROFITBRICKS_API_URL / endpoint issue

### ISSUE THREAD

**Issue by lbobka** [profitbricks/terraform-provider-profitbricks#20]
currently I´m not able to set an other endpoint in main.tf or PROFITBRICKS_API_URL as environment variable.

i.e.

provider "profitbricks" {
  username = "username"
  password = "password"
  endpoint = "https://192.168.1.30"
  timeout = 100
}

or

export PROFITBRICKS_API_URL="192.168.1.1"

is not working.
It´s always pointing to api.profitbricks.com ->185.48.116.14

**Comment by lbobka** [comment]
in your config.go, there is no SetEndpoint function called

**Comment by jasminSPC** [comment]
I'm on it give me 30 minutes and you will have the fix

**Comment by jasminSPC** [comment]
@lbobka There you go https://github.com/profitbricks/terraform-provider-profitbricks/releases/tag/v1.1.2

Sorry for inconvenience

**Comment by lbobka** [comment]
great thx
