### ISSUE TITLE
How to attach boot_cdrom 

### ISSUE THREAD

**Issue by lbobka** [profitbricks/terraform-provider-profitbricks#22]
I want to install a vm via attach cdrom iso image.
It is possible?

**Comment by jasminSPC** [comment]
Unfortunately it is not.

**Comment by jasminSPC** [comment]
Just to elaborate a little bit more. For terraform to run and execute provisioners it needs to be able to ssh into a newly provisioned server. By attaching CD ROMs we are unable to provide password or SSH key which are crucial for provisioners.
