### ISSUE TITLE
Primary nic not correctly detected

### ISSUE THREAD

**Issue by rwunderer** [profitbricks/terraform-provider-profitbricks#24]
I'm facing the following problem with terraform 0.8.5/0.8.6/0.8.7 and terraform-provider-profitbricks v.1.1.1 and v.1.1.2. (amd64)

how to reproduce:
- take main.tf and variables.tf from examples directory
- run terraform apply
- run terraform plan

One would expect terraform to not plan any changes in the last step. Instead the following output is produced:
```
~ profitbricks_server.database
    nic.1455652609.dhcp:                                 "true" => "false"
    nic.1455652609.firewall.#:                           "1" => "0"
    nic.1455652609.firewall.4236383148.icmp_code:        "" => ""
    nic.1455652609.firewall.4236383148.icmp_type:        "" => ""
    nic.1455652609.firewall.4236383148.ip:               "" => ""
    nic.1455652609.firewall.4236383148.ips.#:            "0" => "0"
    nic.1455652609.firewall.4236383148.name:             "SSH" => ""
    nic.1455652609.firewall.4236383148.port_range_end:   "22" => "0"
    nic.1455652609.firewall.4236383148.port_range_start: "22" => "0"
    nic.1455652609.firewall.4236383148.protocol:         "TCP" => ""
    nic.1455652609.firewall.4236383148.source_ip:        "" => ""
    nic.1455652609.firewall.4236383148.source_mac:       "" => ""
    nic.1455652609.firewall.4236383148.target_ip:        "" => ""
    nic.1455652609.firewall_active:                      "true" => "false"
    nic.1455652609.ip:                                   "192.152.28.118" => ""
    nic.1455652609.lan:                                  "2" => "0"
    nic.1455652609.name:                                 "" => ""
    nic.1455652609.nat:                                  "false" => "false"
    nic.715283162.dhcp:                                  "" => "true"
    nic.715283162.firewall.#:                            "0" => "1"
    nic.715283162.firewall.4236383148.icmp_code:         "" => ""
    nic.715283162.firewall.4236383148.icmp_type:         "" => ""
    nic.715283162.firewall.4236383148.ip:                "" => ""
    nic.715283162.firewall.4236383148.ips.#:             "0" => "0"
    nic.715283162.firewall.4236383148.name:              "" => "SSH"
    nic.715283162.firewall.4236383148.port_range_end:    "" => "22"
    nic.715283162.firewall.4236383148.port_range_start:  "" => "22"
    nic.715283162.firewall.4236383148.protocol:          "" => "TCP"
    nic.715283162.firewall.4236383148.source_ip:         "" => ""
    nic.715283162.firewall.4236383148.source_mac:        "" => ""
    nic.715283162.firewall.4236383148.target_ip:         "" => ""
    nic.715283162.firewall_active:                       "" => "true"
    nic.715283162.ip:                                    "" => "192.152.28.118"
    nic.715283162.ips.#:                                 "" => "<computed>"
    nic.715283162.lan:                                   "" => "1"
    nic.715283162.name:                                  "" => ""
    nic.715283162.nat:                                   "" => ""

~ profitbricks_server.webserver
    nic.2580025451.dhcp:                                 "" => "true"
    nic.2580025451.firewall.#:                           "0" => "1"
    nic.2580025451.firewall.4236383148.icmp_code:        "" => ""
    nic.2580025451.firewall.4236383148.icmp_type:        "" => ""
    nic.2580025451.firewall.4236383148.ip:               "" => ""
    nic.2580025451.firewall.4236383148.ips.#:            "0" => "0"
    nic.2580025451.firewall.4236383148.name:             "" => "SSH"
    nic.2580025451.firewall.4236383148.port_range_end:   "" => "22"
    nic.2580025451.firewall.4236383148.port_range_start: "" => "22"
    nic.2580025451.firewall.4236383148.protocol:         "" => "TCP"
    nic.2580025451.firewall.4236383148.source_ip:        "" => ""
    nic.2580025451.firewall.4236383148.source_mac:       "" => ""
    nic.2580025451.firewall.4236383148.target_ip:        "" => ""
    nic.2580025451.firewall_active:                      "" => "true"
    nic.2580025451.ip:                                   "" => "158.222.102.30"
    nic.2580025451.ips.#:                                "" => "<computed>"
    nic.2580025451.lan:                                  "" => "1"
    nic.2580025451.name:                                 "" => ""
    nic.2580025451.nat:                                  "" => ""
    nic.3853071792.dhcp:                                 "true" => "false"
    nic.3853071792.firewall.#:                           "1" => "0"
    nic.3853071792.firewall.4236383148.icmp_code:        "" => ""
    nic.3853071792.firewall.4236383148.icmp_type:        "" => ""
    nic.3853071792.firewall.4236383148.ip:               "" => ""
    nic.3853071792.firewall.4236383148.ips.#:            "0" => "0"
    nic.3853071792.firewall.4236383148.name:             "SSH" => ""
    nic.3853071792.firewall.4236383148.port_range_end:   "22" => "0"
    nic.3853071792.firewall.4236383148.port_range_start: "22" => "0"
    nic.3853071792.firewall.4236383148.protocol:         "TCP" => ""
    nic.3853071792.firewall.4236383148.source_ip:        "" => ""
    nic.3853071792.firewall.4236383148.source_mac:       "" => ""
    nic.3853071792.firewall.4236383148.target_ip:        "" => ""
    nic.3853071792.firewall_active:                      "true" => "false"
    nic.3853071792.ip:                                   "158.222.102.30" => ""
    nic.3853071792.lan:                                  "2" => "0"
    nic.3853071792.name:                                 "" => ""
    nic.3853071792.nat:                                  "false" => "false"
```

Running `terraform apply` will not get rid of the problem, but it will keep changing network configuration, usually ending up with both interfaces of each server in the same network.

Also if firewall rules have been specified for both interfaces on a server, they will all end up at one interface only.

It seems the root of the problem is that terraform is somehow not able to correctly identify the "primary nic". This can be seen in terraform.tfstate file:

```
                "profitbricks_server.webserver": {
                    "type": "profitbricks_server",
...
                            "nic.#": "1",
                            "nic.3853071792.dhcp": "true",
                            "nic.3853071792.firewall.#": "1",
                            "nic.3853071792.firewall.4236383148.icmp_code": "",
                            "nic.3853071792.firewall.4236383148.icmp_type": "",
                            "nic.3853071792.firewall.4236383148.ip": "",
                            "nic.3853071792.firewall.4236383148.ips.#": "0",
                            "nic.3853071792.firewall.4236383148.name": "SSH",
                            "nic.3853071792.firewall.4236383148.port_range_end": "22",
                            "nic.3853071792.firewall.4236383148.port_range_start": "22",
                            "nic.3853071792.firewall.4236383148.protocol": "TCP",
                            "nic.3853071792.firewall.4236383148.source_ip": "",
                            "nic.3853071792.firewall.4236383148.source_mac": "",
                            "nic.3853071792.firewall.4236383148.target_ip": "",
                            "nic.3853071792.firewall_active": "true",
                            "nic.3853071792.ip": "158.222.102.30",
                            "nic.3853071792.ips.#": "1",
                            "nic.3853071792.ips.0": "10.12.24.12",
                            "nic.3853071792.lan": "2",
                            "nic.3853071792.name": "",
                            "nic.3853071792.nat": "false",
                            "primary_ip": "10.12.24.12",
                            "primary_nic": "c25ae311-e1f9-4f5a-81af-5799dca55931",
```
however 10.12.24.12 is the ip address of the other (secondary) interface:
```
                "profitbricks_nic.webserver_nic": {
                    "type": "profitbricks_nic",
                    "depends_on": [
                        "profitbricks_datacenter.main",
                        "profitbricks_server.webserver"
                    ],
                    "primary": {
                        "id": "08929324-002b-4375-872e-349527f3de05",
                        "attributes": {
                            "datacenter_id": "a618bc97-4d2d-4145-aa23-b1928d91a387",
                            "dhcp": "true",
                            "firewall_active": "true",
                            "id": "08929324-002b-4375-872e-349527f3de05",
                            "ips.#": "1",
                            "ips.0": "10.12.24.12",
                            "lan": "2",
                            "name": "",
                            "nat": "false",
                            "server_id": "813d4306-3db1-415d-92f4-927bcfb4a46a"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": ""
                },
```

Interestingly enough, the profitbricks-provider included with terraform 0.8.6/0.8.7 doesn't seem to have this issue but suffers from multiple other problems.

**Comment by jasminSPC** [comment]
Thank you for your feed back. We will look into it.

It would be really helpful if you can list the issues you found with profitbricks provider included with terraform?

**Comment by rwunderer** [comment]
Thanks for the quick response.

With the included profitbricks provider I found that:

- the issue mentioned in #18 still exists: `ssh_key_path` expects a single value, not a list and it accepts only a private (not public) key. I didn't test what it would actually do with that private key.
- when defining a larger infrastructure (I tried with 5 hosts, each with 2 nics and 2 disks) the first `apply` run works fine, but subsequent runs of either refresh, plan or apply abort with `Rate Limit Exceeded`

In v.1.1.2. (or v.1.1.1) `ssh_key_path` works as documented and there are no issues with rate limits.

**Comment by jasminSPC** [comment]
Rate Limit Exceeded is a message from ProfitBricks CloudAPI.

Can you send us your .tf so we can test with the same parameters?

Thanks

**Comment by jasminSPC** [comment]
Just to clarify a little bit more. 
Status Code [429](https://devops.profitbricks.com/api/cloud/v3/#protocol-elements) indicates that more than 300 REST calls per minute have been made. Whenever a server or any other ProfitBricks resource has been created Terraform plugin waits for it to be fully provisioned by checking for its status 50 times (default value) every 10 seconds.

So what might be happening in you case is that all 5 hosts are getting provisioned at the same time and terraform preforms those operations in parallel and by doing that exceeds the limit. 

To overcome this issue I would suggest you make these hosts depend on each other.

**Comment by jasminSPC** [comment]
Also I just checked with Terraform. Although Terraform v0.8.7 has been released it does not contain latest changes we submitted so we will have to wait on that.

**Comment by jasminSPC** [comment]
I confirmed the issue you just reported about tfstate being incorrect. Unfortunately writing nested properties of nested resources like NICs under server is not working properly although we have it implemented here https://github.com/profitbricks/terraform-provider-profitbricks/blob/master/provider/resource_profitbricks_server.go#L496-L515

For which ever reason when plan is called it simply doesn't read existing or correct values. 
I will dig into this and let you know what I find.

**Comment by rwunderer** [comment]
Thanks for looking into the tfstate issue.

Regarding rate limiting with the included provider, I managed to reproduce the issue with the example/main.tf, simply by creating the servers, then doing `terraform refresh; terraform refresh` (it might be necessary to try 2-3 times, results are not consistent).

What's interesting is that this command:

```
terraform refresh; curl --include --request GET --user 'user@example.com:password' https://api.profitbricks.com/cloudapi/v3/datacenters/XXXX/servers/XXXX/nics/XXXX; terraform refresh
```

will in most cases fail on the second "refresh", but the curl call reports `X-RateLimit-Remaining: 299`.

When doing the same test with v.1.1.2. there are no rate limit issues and curl shows `X-RateLimit-Remaining: 291` - which seems more consistent with the number of API-calls one would expect `terraform refresh` to do.

I suppose it makes sense to wait for terraform to update the included provider before pursuing this further.

**Comment by rwunderer** [comment]
I had a closer look and found the reason for the discrepancy between primary_nic and primary_ip: 

- primary_nic is set to the nic located in the public lan
- while primary_ip is simply set to the ip of the first nic

So if the server does not have its first nic in the public lan or does not belong to a public lan at all, primary_nic is wrong.

This patch would bring primary_nic and primary_ip in sync:

```
--- a/provider/resource_profitbricks_server.go
+++ b/provider/resource_profitbricks_server.go
@@ -485,6 +485,7 @@ func resourceProfitBricksServerRead(d *schema.ResourceData, meta interface{}) er
        log.Printf("[DEBUG] dcid, srvrid", dcId, serverId)
 
        nics := profitbricks.ListNics(dcId, serverId)
+       d.Set("primary_nic", nics.Items[0].Id)
 
        nic := profitbricks.GetNic(dcId, serverId, nics.Items[0].Id)
        log.Printf("[DEBUG] ********nic********", nic)
```

The code in https://github.com/profitbricks/terraform-provider-profitbricks/blob/master/provider/resource_profitbricks_server.go#L464-L477 could then be removed, I think.

**Comment by rwunderer** [comment]
Digging further, the heart of the problem seems to be that `nics.Items[0]` is not always the nic defined as part of the server resource (aka primary_nic).

The DCD Webinterface seems to always show the "internally" defined nic as "NIC 0" and the other, separately defined nic, as "NIC 1". 

The API however (as checked with both curl and profitbricks cli) will in some cases return the separate nic first. When this happens tfstate gets confused and the provider sees the same parameters for both primary and secondary nic. It will then naturally try to "fix" the primary nic resulting in this weird plan.

**Comment by jasminSPC** [comment]
I'm aware of that problem. I was thinking maybe to remove computed `pirmary_nic` and then let users select desired nic. That way users would choose on their own which primary_nic to use.

What do you think?

**Comment by rwunderer** [comment]
I agree that's a good idea. Tbh I couldn't think of a reliable way to correctly identify the primary_nic.

**Comment by jasminSPC** [comment]
Actually as it would make sense the problem are the nested values. Server `nic` which is a required field is a nested resource and like I said mentioned [here](https://github.com/profitbricks/terraform-provider-profitbricks/issues/24#issuecomment-281183810) the problem is with TF not writing the values we provide.

**Comment by rwunderer** [comment]
> the problem is with TF not writing the values we provide.
I beg to differ. :-)

The values we are providing are the results of this call:
```
       nic := profitbricks.GetNic(dcId, serverId, nics.Items[0].Id)
```

But `nics.Items[0].Id` is not necessarily the Id of what we consider primary nic.

I'm thinking that maybe we shouldn't change the primary nic at all. After all it's correct immediately after server creation. And from the user's point of view it shouldn't change anyway.

The enclosed patch leaves `primary_nic` as it was at server creation and takes it for setting the nested values. After a quick test it seems to solve the problem for me.

[retain_primary_nic.patch.txt](https://github.com/profitbricks/terraform-provider-profitbricks/files/796077/retain_primary_nic.patch.txt)

Do you think that might be a possible solution?

**Comment by jasminSPC** [comment]
Let me give it a try. You are suggesting that we don't write primary_nic value in read function?

**Comment by rwunderer** [comment]
Exactly. 
Don't write primary_nic in read function. Instead use its value for `GetNic`:

```
-       nic := profitbricks.GetNic(dcId, serverId, nics.Items[0].Id)
+       nic := profitbricks.GetNic(dcId, serverId, primarynic)
```

**Comment by jasminSPC** [comment]
I'm testing it as we speak

**Comment by jasminSPC** [comment]
Unfortunately it doesn't work. It seems that when`	d.Set("primary_nic", server.Entities.Nics.Items[0])` nothing gets written. Therefore this `	primarynic := d.Get("primary_nic").(string)`  doesn't return anything.

**Comment by jasminSPC** [comment]
It seems it worked. The problem was `d.Set("primary_nic", server.Entities.Nics.Items[0])` instead of `d.Set("primary_nic", server.Entities.Nics.Items[0].Id)` in server create. I will be pushing the changes in a moment.

**Comment by jasminSPC** [comment]
I'm uploading version 1.2.1 as we speak. https://github.com/profitbricks/terraform-provider-profitbricks/releases/tag/v1.2.1

**Comment by jasminSPC** [comment]
@rwunderer I've tested it couple of times and it was working fine. Once you confirm that the fix is working can you close the issue. 

And thank you very much for the help.

**Comment by rwunderer** [comment]
It's working perfectly now! Thanks a lot for the quick fix!

**Comment by jasminSPC** [comment]
@rwunderer I've been looking into request limits and just to let you know how those limits work.
The limits apply to all calls made within a given contract. For contracts having multiple users, requests from all users share a common limit.
There are independent limits for read (GET, HEAD) and write operations (POST, PUT, PATCH, DELETE)

If you are able to reproduce the error you were seeing please let us know so we can investigate.

**Comment by rwunderer** [comment]
@jasminSPC sorry for the late reply.

You can reproduce the error, by using the example setup provided with v.1.1.2. with the _internal_ profitbricks provider in tf.

1. Change main.tf for the provider to read:
```
provider "profitbricks" {
  username = "${var.profitbricks_username}"
  password = "${var.profitbricks_password}"
//  timeout = 100
}
```
(as timeout parameter is not supported by the internal provider)

2. run `terraform apply` and get "Rate Limit Exceeded" after a while.


The problem can be solved by adding `retries=100` to the provider definition, as shown in the examples on the terraform website:
```
provider "profitbricks" {
  username = "${var.profitbricks_username}"
  password = "${var.profitbricks_password}" 
  retries = 100
//  timeout = 100
}
```

Whatever this parameter does, it seems the "external" provider v.1.1.2 (and of course v.1.2.0) already does it automatically. 

IMHO instead of investigating problems with the internal profitbricks provider, I'd vote for dumping it completely and instead integrate v.1.2.0 (as it is) as the "official" profitbricks provider within terraform. 

With the changes done in this ticket it has been working perfectly for me ever since.

Of course there might be reasons for having these two provider versions that I'm not aware of, so that's really just a suggestion.

**Comment by jasminSPC** [comment]
Internal provider depends on terraform release cycles so sometimes the changes we push are not released as quickly as the changes we make here.

Meanwhile there has been a new terraform release which is now at 0.8.8. 

We will keep an eye on this just in case.
