### ISSUE TITLE
Release 1.2.0 vs Tag 1.2.1 -> wrong release numbers? 

### ISSUE THREAD

**Issue by angrox** [profitbricks/terraform-provider-profitbricks#32]
The tar.gz releases have the wrong version tags in the filename: 

Tag 1.2.1 -> https://github.com/profitbricks/terraform-provider-profitbricks/releases/download/v1.2.1/terraform-provider-profitbricks-v1.2.0-linux-amd64.tar.gz

**Comment by jasminSPC** [comment]
I just corrected it

If you don't mind checking it and closing the ticket.

Thanks

**Comment by angrox** [comment]
Thank you for the fix!
