### ISSUE TITLE
Changes in server/nic dhcp option is not applied

### ISSUE THREAD

**Issue by angrox** [profitbricks/terraform-provider-profitbricks#41]
Problem: Altering the "dhcp" option in a existing server and reapplying the configuration does not change the value

Example: 
```
resource "profitbricks_server" "worker-instance" {
  count = "${var.count}"
  datacenter_id = "${var.datacenter_id}"
  cores = "${var.cores}"
  ram = "${var.ram}"
  availability_zone = "${var.availability_zone}"
  cpu_family = "AMD_OPTERON"
  name = "${var.target}-${var.hostname}-${format("%02d", count.index+1)}"
  volume {
    image_name = "${var.image}"
    size = "${var.boot_disksize}"
    disk_type = "HDD"
    image_password = "${var.root_password}"
    ssh_key_path = ["${var.ssh_pubkey_path}"]
    name = "${var.target}-${var.hostname}-${format("%02d", count.index+1)}-root"
  }

  nic {
    name = "${var.target}-${var.hostname}-${format("%02d", count.index+1)}-nic-private"
    lan = "${var.private_lan}"
    dhcp = "${var.private_lan_dhcp}"
    firewall_active = false
  }
}
```
Installing a Server with variable private_lan_dhcp==true and afterwards changing the value to false (and reapplying it) does not change the value on the server. 

Versions: 
- Terraform 0.9.3
- Profitbricks Plugin 1.2.3

**Comment by jasminSPC** [comment]
@angrox This seems to be related to nested resources. I will take a deeper look and let you know.

**Comment by jasminSPC** [comment]
It seems there is a problem with the CloudAPI. I tried creating a NIC where DHCP is set to false and each time the NIC is created with DHCP true. I will pass this issue further.
Until it is fixed in CloudAPI there isn't much I can do about it.

**Comment by angrox** [comment]
@jasminSPC Ok. Should we keep this issue open and/or link it to the appropriate issue at Profitbricks CloudAPI?

**Comment by jasminSPC** [comment]
I would leave this open until we are able to verify it is working.

**Comment by jasminSPC** [comment]
@angrox 
I'm sorry for inconvenience but the issue was not with CloudAPI but with GO SDK which has been addressed and the fix is available here https://github.com/profitbricks/terraform-provider-profitbricks/releases/tag/v1.2.5

Please let me know if this helps. 

p.s. I'm going to push this change to Terraform upstream repository but it is going to take some time until it is available there.

**Comment by angrox** [comment]
Works! Thank you very much!
