### ISSUE TITLE
nic.ip doesn't accept ip_block.ips if size=1

### ISSUE THREAD

**Issue by jiansong** [profitbricks/terraform-provider-profitbricks#42]
Example error message:
`* profitbricks_server.firewall: nic.1.ip must be a single value, not a list`

How to reproduce:
Add an IP block has size = 1, e.g.
```
resource "profitbricks_ipblock" "lan_ip" {
  location = "${data.profitbricks_location.loc.id}"
  size     = 1
}
```
Assign the IP block to a NIC
```
  nic {
    lan  = "${profitbricks_lan.internal_lan.id}"
    dhcp = true
    ip   = "${profitbricks_ipblock.lan_ip.ips}"
  }
```

Then run "terraform plan" it will complain above error message.

**Comment by jasminSPC** [comment]
```
ip = "${profitbricks_ipblock.lan_ip.ips.0}"
```

As a refrence you can use [the example](https://github.com/profitbricks/terraform-provider-profitbricks/blob/master/example/main.tf)
