### ISSUE TITLE
Creating multiple LAN objects

### ISSUE THREAD

**Issue by wndhydrnt** [profitbricks/terraform-provider-profitbricks#46]
We would like to try this provider, but the README states that
> Due to a known issue with ProfitBricks Cloud API, the Terraform ProfitBricks Provider does not currently support creating multiple LAN objects. This should be resolved in the near future.

We need to create multiple LAN objects so this issue currently prevents us from using the provider.

The text was added to the README eight months ago. Are there any updates on this?

**Comment by jasminSPC** [comment]
@wndhydrnt Unfortunately not. What you could do is make LANs depend on each other so they won't get provisioned in parallel but one after another.

**Comment by wndhydrnt** [comment]
@jasminSPC Thanks for the hint, I'll try. Maybe add this to the documentation until the issue is resolved so other users know how to work around this?

**Comment by jasminSPC** [comment]
I stand corrected the issue has been fixed. I was able to successfully provision 5 lans like this:

```
resource "profitbricks_lan" "webserver_lan" {
  datacenter_id = "${profitbricks_datacenter.main.id}"
  public = false
  name = "public"
  count = 5
} 
```

Can you please give it a try and let me know if that works out for  you.

**Comment by wndhydrnt** [comment]
I finally managed to test this. I was able to create multiple LAN objects using `count`. Closing.
