### ISSUE TITLE
Multiple NIC declaration problem

### ISSUE THREAD

**Issue by jiansong** [profitbricks/terraform-provider-profitbricks#47]
If I declare multiple NIC(s) inside a "server" resource, it will only pick up the last one, and omit others, for example:
```
  nic {
    name            = "gateway_wan_nic"
    lan             = "${profitbricks_lan.wan_nat.id}"
    dhcp            = false
    ip              = "${profitbricks_ipblock.public_ips.ips.0}"
    firewall_active = false
  }

  nic {
    name            = "gateway_lan_nic"
    lan             = "${profitbricks_lan.internal_lan.id}"
    dhcp            = false
    ip              = "10.0.1.1"
    firewall_active = false
  }

  nic {
    name            = "gateway_dmz_nic"
    lan             = "${profitbricks_lan.dmz.id}"
    dhcp            = false
    ip              = "10.0.2.1"
    firewall_active = false
  }
```
If I declare multiple NIC(s)  (with the resource "profitbricks_nic") outside of a "server" resource, all of then can be picked up by that server, but I still have to declare another at least one NIC inside this "server", otherwise it complain:

` * profitbricks_server.server_name: "nic": required field is not set`

**Comment by jasminSPC** [comment]
A single NIC is required is required to be nested within server resource. We needed this so we could have a single place for "provisioner".
Multiple NICs in server resource are not supported. If you need to declare several other NICs you will have to do it outside server resource. 

In your case declare one NIC within server and the remaining two outside as `profitbrcks_nic`.

**Comment by jiansong** [comment]
Thanks for the feedback and suggestion.
