### ISSUE TITLE
TF Provider Perfomance tends to be very slow

### ISSUE THREAD

**Issue by bechtoldt** [profitbricks/terraform-provider-profitbricks#5]
Hi,

We started to use this TF provider which is huge improvement for automated our infrastructure and infrastructure as code (thx for that!). Unfortunately the provider seems to be slower than the PB backend itself. The whole TF files are very simple so far:

* 1 x profitbricks_ipblock
* 5 x profitbricks_server, each 1xprofitbricks_nic and 1xprofitbricks_firewall
* everything is located in the DC in Karlsruhe

Setting up such an infrastructure takes 15-20 minutes. Shutting (``destroy``) it down, too. (!) Creating or deleting the resources via PB GUI or CLI is way faster. Service timeouts (see below) also happen from time to time.

> TERRAFORM_VERSION=0.7.3
> TF_PB_VERSION=v1.0.3

TB Log: https://gist.github.com/bechtoldt/dcbaf7870d0666990f5fc57ef5bf4e1a

I might be wrong about the execution time TF vs. GUI/CLI, so I would be interested in your benchmarks. :)

**Comment by jasminSPC** [comment]
Can you send me your TF file so I can create the same infrastructure? (don't forget to remove your private data from it)

**Comment by bechtoldt** [comment]
Hi, sent via mail. thx!

**Comment by jasminSPC** [comment]
Also to clarify what we are doing with TF plugin.

Each object that is created we wait until the object is `AVAILABLE`, which means for every object created we query REST API to retrieve request status, which is adding some time to the wait. 
Also if you are using TF `provisioner` that adds more time to the provisioning process.

This [example](https://github.com/profitbricks/terraform-provider-profitbricks/blob/master/example/main.tf) I started at 3:15 PM and it finished at 3:22 PM.

I'm going to take a look at the example you sent me.

**Comment by jasminSPC** [comment]
It seems that when you are having 5 concurrent server objects created the API simply slows down. I will dig it a little more and get back to you

**Comment by bechtoldt** [comment]
Great to see you can reproduce it. Take all the time you need.

**Comment by jasminSPC** [comment]
It took me 20 minutes to finish.
What I noticed that the whole process simply slows down after a while.

What I did i ran another tf file next to your infrastructure and it seems the overall process just slows down after a while.

**Comment by jasminSPC** [comment]
I'm going to close this ticket. If you have anything to add, please go ahead and reopen it.

**Comment by bechtoldt** [comment]
> Ok so I used the example I sent you and modify it to create 5 identical servers with 50gb of disk > space and it took 10 minutes. To delete the servers takes a little bit less than it takes to create > them.
> Your example, which is slightly complex, took about 15 minutes. Deleting is same as above.

Lucky you, i.e. destroying a LAN isn't possible right now (due to *timeout expired*). For now I blame the PB backend and rerun my commands using the TF debug loglevel....

![screen shot 2016-10-19 at 15 42 40](https://cloud.githubusercontent.com/assets/1507504/19521354/96d7f6f4-9613-11e6-81bd-4eb2100fa378.png)

**Comment by jasminSPC** [comment]
This message is from the plugin which means that the timeout has expired. Default value is 50 retries but you could extend it indefinitely like this:

```
provider "profitbricks" {
    timeout = 1000
}
``` 

The integer value represents number of retries. Retry duration is the time it takes to make the REST call to ProfitBricks + 10 second of timeout between retries.

**Comment by bechtoldt** [comment]
well, removing a LAN (just the LAN, without any hosts) shouldn't take more than 10 minutes..

I've deleted it manually.

**Comment by jasminSPC** [comment]
I agree it doesn't make any sense.

**Comment by jiansong** [comment]
I also ran into this problem, something must be wrong in the backend, creating 3 networks should not take that long time, I had to interrupt the applying, meanwhile the GUI is still showing "In Progress..."

```
data.profitbricks_location._location: Refreshing state...
data.profitbricks_image._image: Refreshing state...
[... repeated lines ...]
data.profitbricks_image._image: Refreshing state...
module.public_ips.profitbricks_ipblock.public_ips: Creating...
  ips.#:    "" => "<computed>"
  location: "" => "de/fra"
  size:     "" => "3"
module.main_datacenter.profitbricks_datacenter._datacenter: Creating...
  description: "" => "Cloud datacenter at Frankfurt"
  location:    "" => "de/fra"
  name:        "" => "iaas_vdc"
module.main_datacenter.profitbricks_datacenter._datacenter: Creation complete (ID: 6d4b25f2-4d01-4936-a59d-xxxxxxxxxxxx)
module.network_wan.profitbricks_lan._network: Creating...
  datacenter_id: "" => "6d4b25f2-4d01-4936-a59d-xxxxxxxxxxxx"
  name:          "" => "WAN"
  public:        "" => "true"
module.network_lan.profitbricks_lan._network: Creating...
  datacenter_id: "" => "6d4b25f2-4d01-4936-a59d-xxxxxxxxxxxx"
  name:          "" => "LAN"
  public:        "" => "false"
module.network_dmz.profitbricks_lan._network: Creating...
  datacenter_id: "" => "6d4b25f2-4d01-4936-a59d-xxxxxxxxxxxx"
  name:          "" => "DMZ"
  public:        "" => "false"
module.public_ips.profitbricks_ipblock.public_ips: Creation complete (ID: 3121a179-2365-46c1-be5e-xxxxxxxxxxxx)
module.network_wan.profitbricks_lan._network: Still creating... (10s elapsed)
[...]
module.network_dmz.profitbricks_lan._network: Still creating... (44m0s elapsed)
^CInterrupt received.
```
