### ISSUE TITLE
Feature: Enable setting availabilityZone for volume

### ISSUE THREAD

**Issue by invadersmustdie** [profitbricks/terraform-provider-profitbricks#9]
As of APIv3 it's possible to set the parameter availabilityZone for volumes. (https://devops.profitbricks.com/api/cloud/v3/#availability-zones-for-storage-volumes)

This isn't yet implemented in the TF provider. Any chance to get implemented within the next release? :)

**Comment by jasminSPC** [comment]
We haven't gotten to that point yet. Most likely one of the future releases will cover v3
